using TypeSpec.Versioning;

namespace AzureOpenAI;

/**
 * Known service API versions for Azure OpenAI.
 */
enum AzureOpenAIServiceApiVersion {
  /**
   * The 2024-02-15-preview service API version label.
   */
  v2024_02_15_preview: "2024-02-15-preview",

  /**
   * The 2024-04-01-preview service API version label.
   */
  v2024_04_01_preview: "2024-04-01-preview",

  /**
   * The 2024-06-01 (stable) service API version label.
   */
  v2024_06_01: "2024-06-01",

  /**
   * The 2024-08-01-preview service API version label.
   */
  v2024_08_01_preview: "2024-08-01-preview",

  /**
   * The 2024-09-01-preview service API version label.
   */
  v2024_09_01_preview: "2024-09-01-preview",

  /**
   * The 2024-10-01-preview service API version label.
   */
  v2024_10_01_preview: "2024-10-01-preview",

  /**
   * The 2024-10-21 (stable) service API version label.
   */
  v2024_10_21: "2024-10-21",

  /**
   * The 2024-12-01-preview service API version label.
   */
  v2024_12_01_preview: "2024-12-01-preview",

  /**
   * The 2025-01-01-preview service API version label.
   */
  v2025_01_01_preview: "2025-01-01-preview",

  /**
   * The 2025-03-01-preview service API version label.
   */
  v2025_03_01_preview: "2025-03-01-preview",
}
